Repository xmtp/proto, pull requests merged in 2024-05, with the labels that each got.

#180 Inbox ID updates
  proto/mls/database/intents.proto
  proto/mls/message_contents/group_metadata.proto
Labels: inbox-id

#178 Protos for credential validation of Inbox IDs
  proto/mls_validation/v1/service.proto
Labels: inbox-id

#175 Mutable Group Permissions
  proto/mls/message_contents/group_metadata.proto
  proto/mls/message_contents/group_mutable_metadata.proto
  proto/mls/message_contents/group_permissions.proto
Labels: Group Chat - Prod

#184 feat: added intent for updating admin lists
  proto/mls/database/intents.proto
Labels: released, Group Chat - Prod
